[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "5000" }
PYTHONUNBUFFERED = { default = "1" }
